'use client';
import {useState} from 'react';
import {Dish,Ingredient} from '@/lib/model';
import {Modal,Art,Section,Pick,Toggle,Primary} from './ui';
import {PlusCircle,MinusCircle,ArrowUp,ArrowDown,Camera} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {singleEmoji,photoPreview} from '@/lib/dish-cover';
const foodEmoji=['🍽️','🍝','🍕','🍔','🌮','🥗','🍜','🍲','🍛','🥟','🍣','🍤','🐟','🥩','🍗','🥓','🍳','🥞','🧇','🥪','🥐','🥖','🧀','🥔','🥦','🥑','🍅','🍓','🍎','🍌','🍰','🧁','🍪','🍦','☕','🥤'];
export function Editor({initial,categories,save,close}:{initial:Dish;categories:string[];save:(dish:Dish)=>Promise<void>;close:()=>void}){const[d,set]=useState(structuredClone(initial));const[cover,setCover]=useState(initial.photo?'photo':'emoji');const[emojiInput,setEmojiInput]=useState(initial.symbol);const[details,setDetails]=useState(!!initial.name);const[newName,setNewName]=useState('');const[newCategory,setNewCategory]=useState('');const[newVariation,setNewVariation]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
const update=(p:Partial<Dish>)=>set(v=>({...v,...p}));const row=(id:string,p:Partial<Ingredient>)=>update({ingredients:d.ingredients.map(i=>i.id===id?{...i,...p}:i)});
const addIngredient=()=>{if(!newName.trim())return;update({ingredients:[...d.ingredients,{id:crypto.randomUUID(),name:newName.trim(),amount:'',unit:'',available:false}]});setNewName('')};
async function commit(){setBusy(true);setError('');try{const ingredients=[...d.ingredients,...(newName.trim()?[{id:crypto.randomUUID(),name:newName.trim(),amount:'',unit:'',available:false}]:[])].filter(i=>i.name.trim());await save({...d,photo:cover==='photo'?d.photo:undefined,name:d.name.trim(),category:newCategory.trim()||d.category,ingredients,ingredientsAtHome:ingredients.length?ingredients.every(i=>i.available):d.ingredientsAtHome,variations:[...d.variations,...(newVariation.trim()?[newVariation.trim()]:[])]});close()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
async function upload(file?:File){if(!file)return;setBusy(true);setError('');try{update({photo:await photoPreview(file)});setCover('photo')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
return <Modal title={initial.name?'Редактировать':'Новое блюдо'} close={close} action={<button className="save" onClick={commit} disabled={busy||!d.name.trim()}>{busy?'Сохраняем…':initial.name?'Сохранить':'Добавить'}</button>}><div className="editor">{error&&<p role="alert" className="error">{error}</p>}<div className="form-group"><input className="name-input" aria-label="Название блюда" placeholder="Название блюда" value={d.name} onChange={e=>update({name:e.target.value})}/><div className="cover-picker"><Tabs value={cover} onValueChange={setCover}><TabsList className="segments" aria-label="Обложка блюда"><TabsTrigger value="emoji">Эмодзи</TabsTrigger><TabsTrigger value="photo">Фото</TabsTrigger></TabsList></Tabs><Art dish={{...d,photo:cover==='photo'?d.photo:undefined}} large/>{cover==='photo'?<><label className="photo-picker"><span><Camera size={19}/>{busy?'Обрабатываем…':d.photo?'Заменить фото':'Выбрать фото'}</span><input type="file" accept="image/*" disabled={busy} onChange={e=>{upload(e.target.files?.[0]);e.target.value=''}}/></label>{d.photo&&<button className="text-button danger" onClick={()=>update({photo:undefined})}>Убрать фото</button>}</>:<><div className="emoji-grid" role="group" aria-label="Эмодзи блюда">{foodEmoji.map(symbol=><button type="button" key={symbol} aria-label={`Выбрать ${symbol}`} aria-pressed={d.symbol===symbol} onClick={()=>{update({symbol});setEmojiInput(symbol)}}>{symbol}</button>)}</div><label className="form-row"><span>Свой эмодзи</span><input className="emoji-input" aria-label="Свой эмодзи" placeholder="🍽️" value={emojiInput} onChange={e=>{setEmojiInput(e.target.value);const symbol=singleEmoji(e.target.value);if(symbol)update({symbol})}} onBlur={()=>setEmojiInput(d.symbol)} autoComplete="off"/></label><p className="hint">Выберите из списка или вставьте один эмодзи с клавиатуры.</p></>}</div></div>{!initial.name&&<><p className="hint">Можно сохранить уже сейчас. Или добавить детали ниже.</p><Toggle label="Добавить детали" value={details} onChange={setDetails}/></>}{details&&<>
<Section title="О блюде"><div className="form-row"><span>Категория</span><Pick label="Категория" value={d.category} options={[...new Set([...categories,d.category])]} onChange={v=>update({category:v})}/></div><div className="form-row"><input placeholder="Своя категория" value={newCategory} onChange={e=>setNewCategory(e.target.value)}/><button aria-label="Добавить категорию" disabled={!newCategory.trim()} onClick={()=>{update({category:newCategory.trim()});setNewCategory('')}}><PlusCircle/></button></div><Stepper label={`${d.cookingTime} минут`} value={d.cookingTime} min={0} max={360} step={5} set={v=>update({cookingTime:v})}/><Stepper label={`Порций: ${d.servings}`} value={d.servings} min={1} max={24} set={v=>update({servings:v})}/><div className="form-row"><span>Сложность</span><Pick label="Сложность" value={d.difficulty} options={['Просто','Немного усилий','Для особого случая']} onChange={v=>update({difficulty:v})}/></div></Section>
<Section title="Ингредиенты" hint="Раскройте строку для количества и единиц. Отметка «Есть дома» учитывается при выборе.">{d.ingredients.map((i,index)=><details key={i.id} className="ingredient-edit"><summary><span className={i.available?'sage':''}>{i.available?'✓':'○'}</span><span>{i.name}</span><small>{i.amount} {i.unit}</small></summary><div className="form-row"><input aria-label="Название ингредиента" value={i.name} onChange={e=>row(i.id,{name:e.target.value})}/></div><div className="form-row"><input aria-label="Количество" placeholder="Количество" value={i.amount} onChange={e=>row(i.id,{amount:e.target.value})}/><Pick label="Единица" value={i.unit} options={['','г','кг','мл','л','шт.','ст. л.','ч. л.','по вкусу']} onChange={v=>row(i.id,{unit:v})}/></div><Toggle label="Есть дома" value={i.available} onChange={v=>row(i.id,{available:v})}/><div className="form-row"><button className="danger" onClick={()=>update({ingredients:d.ingredients.filter(r=>r.id!==i.id)})}>Удалить</button><span/><button aria-label="Выше" disabled={index===0} onClick={()=>{const a=[...d.ingredients];[a[index-1],a[index]]=[a[index],a[index-1]];update({ingredients:a})}}><ArrowUp size={18}/></button><button aria-label="Ниже" disabled={index===d.ingredients.length-1} onClick={()=>{const a=[...d.ingredients];[a[index+1],a[index]]=[a[index],a[index+1]];update({ingredients:a})}}><ArrowDown size={18}/></button></div></details>)}<div className="form-row"><input placeholder="Новый ингредиент" value={newName} onChange={e=>setNewName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addIngredient()}}}/><button aria-label="Добавить ингредиент" disabled={!newName.trim()} onClick={addIngredient}><PlusCircle/></button></div></Section>
<Section title="Как ещё готовим" hint="Замены и домашние версии одного блюда.">{d.variations.map((v,i)=><div className="form-row" key={i}><input aria-label="Вариант" value={v} onChange={e=>update({variations:d.variations.map((x,n)=>n===i?e.target.value:x)})}/><button aria-label="Удалить вариант" className="danger" onClick={()=>update({variations:d.variations.filter((_,n)=>n!==i)})}><MinusCircle/></button></div>)}<div className="form-row"><input placeholder="Например, с курицей" value={newVariation} onChange={e=>setNewVariation(e.target.value)}/><button aria-label="Добавить вариант" disabled={!newVariation.trim()} onClick={()=>{update({variations:[...d.variations,newVariation.trim()]});setNewVariation('')}}><PlusCircle/></button></div></Section>
<Section title="Особенности"><Toggle label="Любимое" value={d.favorite} onChange={v=>update({favorite:v})}/>{!d.ingredients.length&&<Toggle label="Есть продукты дома" value={d.ingredientsAtHome} onChange={v=>update({ingredientsAtHome:v})}/>}<Toggle label="Лёгкое блюдо" value={d.light} onChange={v=>update({light:v})}/><Toggle label="Не нужно готовить" value={d.noCooking} onChange={v=>update({noCooking:v})}/></Section><Section title="Заметка"><textarea aria-label="Заметка" placeholder="Ваши маленькие секреты" value={d.notes} onChange={e=>update({notes:e.target.value})}/></Section><Section title="Последнее приготовление"><Toggle label="Указать дату" value={!!d.lastCookedAt} onChange={v=>update({lastCookedAt:v?new Date().toISOString():undefined})}/>{d.lastCookedAt&&<input aria-label="Дата приготовления" type="date" max={new Date().toISOString().slice(0,10)} value={d.lastCookedAt.slice(0,10)} onChange={e=>{if(e.target.value)update({lastCookedAt:new Date(e.target.value+'T12:00:00').toISOString()})}}/>}</Section></>}</div></Modal>}
function Stepper({label,value,set,min,max,step=1}:{label:string;value:number;set:(n:number)=>void;min:number;max:number;step?:number}){return <div className="form-row"><span>{label}</span><div className="stepper"><button aria-label={`Уменьшить: ${label}`} disabled={value<=min} onClick={()=>set(Math.max(min,value-step))}>−</button><button aria-label={`Увеличить: ${label}`} disabled={value>=max} onClick={()=>set(Math.min(max,value+step))}>+</button></div></div>}
