import {db,identity,setSession,token,hash,checkOrigin,failure} from '@/lib/server';
import {defaultHome,demo} from '@/lib/model';
import {z} from 'zod';
export const dynamic='force-dynamic';
const ingredient=z.object({id:z.string().max(100),name:z.string().trim().min(1).max(250),amount:z.string().max(100),unit:z.string().max(50),available:z.boolean()});
const dish=z.object({id:z.string().min(1).max(100),name:z.string().trim().min(1).max(200),symbol:z.string().max(20),photo:z.string().regex(/^\/api\/photos\/[a-zA-Z0-9-]+$/).optional(),category:z.string().trim().min(1).max(80),cookingTime:z.number().int().min(0).max(360),difficulty:z.string().max(80),ingredients:z.array(ingredient).max(100),notes:z.string().max(10000),favorite:z.boolean(),createdAt:z.string().datetime(),lastCookedAt:z.string().datetime().optional(),cookedDates:z.array(z.string().datetime()).max(2000),ingredientsAtHome:z.boolean(),light:z.boolean(),noCooking:z.boolean(),servings:z.number().int().min(1).max(24),variations:z.array(z.string().max(500)).max(50),version:z.number().int().optional()});
const schemas={dish,home:z.object({name:z.string().trim().min(1).max(150),members:z.array(z.object({id:z.enum(['first','second']),name:z.string().trim().min(1).max(80),notes:z.string().max(1000)})).length(2),categories:z.array(z.string().trim().min(1).max(80)).max(50),onboarded:z.boolean(),version:z.number().optional()}),plan:z.object({id:z.string().max(100),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),meal:z.enum(['Завтрак','Обед','Ужин']),dishId:z.string().max(100),version:z.number().optional()}),preference:z.object({id:z.string().max(200),userId:z.enum(['first','second']),dishId:z.string().max(100),status:z.enum(['Люблю','Нейтрально','Не люблю']),version:z.number().optional()})};
export async function GET(){try{const who=await identity();if(!who)return Response.json({needsHome:true},{headers:{'Cache-Control':'no-store'}});const {results}=await db().prepare('SELECT kind,id,payload,version FROM records WHERE home_id=?').bind(who.home_id).all<{kind:string;id:string;payload:string;version:number}>();const get=(kind:string)=>results.filter(r=>r.kind===kind).map(r=>({...JSON.parse(r.payload),version:r.version}));return Response.json({home:get('home')[0],dishes:get('dish'),plans:get('plan'),preferences:get('preference'),member:who.member},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(request:Request){try{checkOrigin(request);if(Number(request.headers.get('content-length')||0)>500000)return Response.json({error:'Слишком много данных'},{status:413});const body=await request.json() as Record<string,unknown>;const who=await identity();
if(body.action==='create'){if(who)return Response.json({ok:true});const home=crypto.randomUUID();const homeData={...defaultHome,onboarded:true};const statements=[db().prepare('INSERT INTO homes(id) VALUES(?)').bind(home),db().prepare('INSERT INTO records(home_id,kind,id,payload) VALUES(?,?,?,?)').bind(home,'home','home',JSON.stringify(homeData))];if(body.demo===true)for(const d of demo)statements.push(db().prepare('INSERT INTO records(home_id,kind,id,payload) VALUES(?,?,?,?)').bind(home,'dish',d.id,JSON.stringify(d)));await db().batch(statements);await setSession(home,'first',request);return Response.json({ok:true})}
if(body.action==='join'){const invite=z.string().min(40).max(200).parse(body.token);const h=await hash(invite);const found=await db().prepare('SELECT id FROM homes WHERE invite_hash=? AND invite_expires>?').bind(h,Date.now()).first<{id:string}>();if(!found)throw new Error('Приглашение уже использовано или устарело. Попросите новую ссылку.');const used=await db().prepare('UPDATE homes SET invite_hash=NULL,invite_expires=NULL WHERE id=? AND invite_hash=?').bind(found.id,h).run();if(!used.meta.changes)throw new Error('Ссылка уже использована.');await setSession(found.id,'second',request);return Response.json({ok:true})}
if(!who)return Response.json({error:'Сначала создайте дом или откройте приглашение.'},{status:401});
if(body.action==='invite'){if(who.member!=='first')throw new Error('Приглашения создаёт владелец дома.');const invite=token();await db().prepare('UPDATE homes SET invite_hash=?,invite_expires=? WHERE id=?').bind(await hash(invite),Date.now()+7*86400000,who.home_id).run();return Response.json({token:invite})}
if(body.action==='save'){const kind=z.enum(['dish','home','plan','preference']).parse(body.kind);const value=schemas[kind].parse(body.value);const id=kind==='home'?'home':('id' in value?value.id:'');if(kind==='preference'){const p=value as z.infer<typeof schemas.preference>;if(p.id!==`${p.userId}-${p.dishId}`)throw new Error('Некорректная отметка');}
if(kind==='plan'||kind==='preference'){const dishId=(value as {dishId:string}).dishId;if(!await db().prepare("SELECT id FROM records WHERE home_id=? AND kind='dish' AND id=?").bind(who.home_id,dishId).first())throw new Error('Блюдо уже удалено. Обновите меню.');}
const version=value.version;const clean={...value};delete clean.version;const payload=JSON.stringify(clean);if(payload.length>400000)throw new Error('Слишком большая запись');
if(version){const r=await db().prepare('UPDATE records SET payload=?,version=version+1 WHERE home_id=? AND kind=? AND id=? AND version=?').bind(payload,who.home_id,kind,id,version).run();if(!r.meta.changes)return Response.json({error:'Это уже изменили на другом телефоне. Обновите данные и сохраните ещё раз.'},{status:409});}else{const r=await db().prepare('INSERT OR IGNORE INTO records(home_id,kind,id,payload) VALUES(?,?,?,?)').bind(who.home_id,kind,id,payload).run();if(!r.meta.changes)return Response.json({error:'Запись уже существует. Обновите данные.'},{status:409});}return Response.json({ok:true})}
if(body.action==='delete'){const kind=z.enum(['dish','plan']).parse(body.kind);const id=z.string().max(100).parse(body.id);const statements=[db().prepare('DELETE FROM records WHERE home_id=? AND kind=? AND id=?').bind(who.home_id,kind,id)];if(kind==='dish')for(const k of ['plan','preference'])statements.push(db().prepare('DELETE FROM records WHERE home_id=? AND kind=? AND json_extract(payload,\'$.dishId\')=?').bind(who.home_id,k,id));await db().batch(statements);return Response.json({ok:true})}
throw new Error('Неизвестное действие');}catch(e){return failure(e)}}
